step1: inputimage.txt
  revstring -i1 inputimage.txt -o1 step1out1.txt

step2: step1
  revstring -i1 step1out1.txt -o1 step2out1.txt

step3: step2
  revstring -i1 step2out1.txt -o1 step3out1.txt

runAlgorithm: step3
